version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - C:/Users/Alex/volumes/credit:/var/lib/postgresql
    ports:
      - "8089:5432"